# Generated by Django 3.2.11 on 2022-08-02 05:33

import app0724.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0724', '0003_goodmobilenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to=app0724.models.image_upload_to)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('download_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
