# Generated by Django 3.2.11 on 2022-08-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0724', '0004_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microservice_name', models.CharField(max_length=32, verbose_name='服务名称')),
                ('microservice_desc', models.CharField(max_length=200, verbose_name='服务备注')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='服务创建时间')),
                ('is_running', models.SmallIntegerField(choices=[(0, '未运行'), (1, '正在运行')], default=0, verbose_name='是否在运行')),
                ('is_delete', models.SmallIntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(auto_now=True, verbose_name='删除时间')),
            ],
        ),
    ]
