# Generated by Django 3.2.15 on 2022-10-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0724', '0005_microservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodmobilenumber',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级'), (4, '四级'), (5, '五级')], default=2, verbose_name='账号级别'),
        ),
    ]
