# Generated by Django 3.2.15 on 2022-10-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, verbose_name='用户名')),
                ('message', models.CharField(max_length=100, verbose_name='聊天内容')),
                ('send_message_time', models.DateTimeField(auto_now=True, verbose_name='信息发送时间')),
            ],
        ),
    ]
