# Generated by Django 3.2.15 on 2022-10-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='send_message_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='信息发送时间'),
        ),
    ]
