# Generated by Django 3.2.15 on 2022-10-31 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1011', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='用户',
        ),
    ]
