# Generated by Django 3.2.15 on 2022-10-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1011', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
